name: default
channels:
  - conda-forge
dependencies:
  - astor=0.8.1
  - asttokens=2.4.1
  - attr=2.5.1
  - attrs=24.2.0
  - beautifulsoup4=4.12.3
  - boto3=1.35.63
  - botocore=1.35.63
  - brotli=1.1.0
  - brotli-python=1.1.0
  - bs4=4.12.3
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.4.0
  - comm=0.2.2
  - contourpy=1.3.1
  - cycler=0.12.1
  - debugpy=1.8.8
  - decorator=5.1.1
  - econtools=0.3.2
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - gmpy2=2.1.5
  - graphlib-backport=1.0.3
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.10
  - imbalanced-learn=0.12.4
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.5
  - interface_meta=1.3.0
  - ipykernel=6.29.5
  - ipython=8.29.0
  - jedi=0.19.2
  - jmespath=1.0.1
  - joblib=1.4.2
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - jupytext=1.16.4
  - kiwisolver=1.4.7
  - linearmodels=6.1
  - markdown-it-py=3.0.0
  - matplotlib=3.9.2
  - matplotlib-inline=0.1.7
  - mdit-py-plugins=0.4.2
  - mdurl=0.1.2
  - metaflow=2.12.26
  - mpmath=1.3.0
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - numpy=2.1.3
  - openssl=3.4.0
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - patsy=1.0.1
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.3.1
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.1.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.18.0
  - pyhdfe=0.2.0
  - pyparsing=3.2.0
  - python=3.12.7
  - python-dateutil=2.9.0
  - python-fastjsonschema=2.20.0
  - python-tzdata=2024.2
  - pytz=2024.1
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - requests=2.32.3
  - rich=13.9.4
  - scikit-learn=1.5.2
  - scipy=1.14.1
  - seaborn=0.13.2
  - setuptools=75.5.0
  - six=1.16.0
  - soupsieve=2.5
  - stack_data=0.6.2
  - statsmodels=0.14.4
  - sympy=1.13.3
  - threadpoolctl=3.5.0
  - tomli=2.1.0
  - toolz=1.0.0
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing-extensions=4.12.2
  - tzdata=2024b
  - urllib3=2.2.3
  - wcwidth=0.2.13
  - wrapt=1.16.0
  - zipp=3.21.0

